'use client'

import { useState } from 'react'
import Image from 'next/image'
import { ArrowRight, ArrowUpRight, Check, ChevronDown, Leaf, ShieldCheck, Sprout, Sun, Waves } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Brand, Eyebrow, StartCampaign } from './shared'
import { cn } from '@/lib/utils'

const projects = [
  { category: 'Clean energy', title: 'A brighter future starts with solar.', description: 'Help community spaces turn sunlight into learning, connection, and possibility.', image: '/images/community-solar.png', alt: 'Illustrative solar installation with community technicians', icon: Sun, milestone: 'Install panels, share installation evidence, then review the next stage.' },
  { category: 'Reforestation', title: 'More roots. A more resilient tomorrow.', description: 'Bring people together to restore forest habitats and care for the land.', image: '/images/forest.jpg', alt: 'Dense green forest canopy', icon: Sprout, milestone: 'Prepare the land, document planting, then assess ongoing care.' },
  { category: 'Ocean care', title: 'Give our coastlines a fresh start.', description: 'Support community-led coastal care, one collective action at a time.', image: '/images/ocean.jpeg', alt: 'Ocean and coastline from the original EcoFundMe collection', icon: Waves, milestone: 'Organize the cleanup, publish evidence, then review follow-up work.' },
]
const faqs = [
  { q: 'How does a reply turn into support?', a: 'The EcoFundMe bot connects an X reply to a campaign donation flow. The first donation opens campaign escrow, and the creator is brought into identity verification and milestone setup before they can withdraw. The thread becomes a place to follow the campaign’s updates.' },
  { q: 'Who decides when the next milestone is funded?', a: 'Backers review the current milestone’s evidence and participate in campaign governance. The outcome determines whether the next release can proceed. Voting thresholds, participation requirements, and dispute rules are set by the deployed protocol; this page does not assume that silence is approval.' },
  { q: 'What does zero-knowledge voting mean for me?', a: 'Zero-knowledge proofs allow a system to verify a statement without revealing its underlying private inputs. In voting, that can support privacy-preserving eligibility and ballot verification. Exactly which identity or ballot information stays private depends on EcoFundMe’s deployed protocol—not a blanket anonymity guarantee.' },
  { q: 'Can I use campaign funds outside the platform?', a: 'Released funds can support campaign spending through payment cards, bank transfers, and supported mobile-money routes. EcoFundMe supports fiat outlets across more than 20 African countries. Individual card networks, currencies, fees, and payout methods vary by provider, country, and eligibility.' },
  { q: 'Do I need to manage a crypto wallet?', a: 'The repository describes a custodial USDC wallet on Base, with no seed phrase for you to manage. Blockchain supports the funding record; you can focus on the campaign. Donations are not investments, and there is no EcoFundMe token, yield, or equity reward.' },
  { q: 'Are the campaigns on this page live?', a: 'No. These are clearly marked example campaign stories for the landing-page experience. No donations, votes, card purchases, or payouts happen in this preview. Live campaign listings and transactions require connection to the production platform.' },
]

export function CampaignsAndFooter() {
  const [filter, setFilter] = useState('All causes')
  const [selected, setSelected] = useState<(typeof projects)[number] | null>(null)
  const visible = filter === 'All causes' ? projects : projects.filter(project => project.category === filter)
  return <><section id="campaigns" className="campaigns-section"><div className="page-container"><div className="section-heading-row"><div><Eyebrow>The possibilities</Eyebrow><h2>Find your kind of change.</h2></div><p>Different causes. One shared tomorrow.<br />Explore what community-powered action can look like.</p></div><div className="campaign-toolbar"><div className="campaign-filters" aria-label="Filter example campaigns">{['All causes', ...projects.map(project => project.category)].map(category => <button key={category} onClick={() => setFilter(category)} className={cn(filter === category && 'active')} aria-pressed={filter === category}>{category === 'All causes' && <Leaf size={15} />}{category}</button>)}</div><span>Illustrative campaigns · not accepting donations</span></div><div className="campaign-grid">{visible.map(project => <article className="campaign-card" key={project.title}><button className="campaign-image-button" onClick={() => setSelected(project)} aria-label={`Explore example: ${project.title}`}><Image src={project.image} fill sizes="(max-width: 640px) 90vw, (max-width: 1000px) 45vw, 380px" alt={project.alt} /><span className="campaign-category"><project.icon size={14} />{project.category}</span><span className="campaign-open"><ArrowUpRight size={20} /></span></button><div className="campaign-card-copy"><h3><button onClick={() => setSelected(project)}>{project.title}</button></h3><p>{project.description}</p><button className="text-link" onClick={() => setSelected(project)}>Explore the story<ArrowRight size={16} /></button></div></article>)}</div></div></section>
    <Dialog open={!!selected} onOpenChange={open => { if (!open) setSelected(null) }}><DialogContent className="campaign-dialog sm:max-w-lg">{selected && <><DialogHeader><p className="eyebrow">EXAMPLE CAMPAIGN</p><DialogTitle>{selected.title}</DialogTitle><DialogDescription>{selected.description}</DialogDescription></DialogHeader><div className="dialog-campaign-image"><Image src={selected.image} alt={selected.alt} fill sizes="500px" /></div><h3>What progress could look like</h3><p>{selected.milestone}</p><p className="fine-print"><ShieldCheck size={17} />This is an illustrative story, not an active fundraiser. No payment is collected.</p><Button onClick={() => setSelected(null)} variant="outline">Back to the possibilities<ArrowRight data-icon="inline-end" /></Button></>}</DialogContent></Dialog>
    <section id="questions" className="faq-section"><div className="page-container faq-layout"><div><Eyebrow>A little clarity</Eyebrow><h2>Good questions.<br />Straight answers.</h2><p className="section-description">Big ideas deserve a little explanation.</p></div><div className="faq-list">{faqs.map(faq => <details key={faq.q}><summary>{faq.q}<ChevronDown size={18} /></summary><p>{faq.a}</p></details>)}</div></div></section>
    <section className="closing-section dark-surface"><div className="page-container closing-inner"><div className="closing-mark"><Image src="/images/ecofundme-logo.png" width={58} height={58} alt="" /></div><Eyebrow light>It starts with us</Eyebrow><h2>The next good thing<br />could start with <span>you.</span></h2><p>A post. A reply. A little belief.<br />Let&apos;s see how far it can go.</p><StartCampaign label="Be part of the change" /><a className="closing-secondary" href="#campaigns">Find a cause you care about<ArrowUpRight size={16} /></a></div></section>
    <footer className="site-footer dark-surface"><div className="page-container"><div className="footer-top"><Brand /><p>People-powered. Progress-proven.</p><nav aria-label="Footer navigation"><a href="#how-it-works">How it works</a><a href="#governance">Governance</a><a href="#money">Cards & payouts</a><a href="#questions">FAQs</a></nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} EcoFundMe. For a better tomorrow.</span><span><span className="live-dot" />Powered by blockchain. Built for people.</span></div><p className="footer-disclosure">Donations are not investments. Illustrative stories and product interfaces are not live transactions. Financial services are subject to provider terms, verification, and regional availability.</p></div></footer></>
}
